package com.jeff.notekeeper.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a Note entity in the Room database.
 * The @Entity annotation marks this class as a table in the database.
 */
@Entity(tableName = "notes")
data class Note(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Unique ID for each note, auto-generated by Room.
    val title: String, // Title of the note.
    val content: String // Content or body of the note.
)